kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    pull: default
    image: rancher/dapper:v0.5.2
    commands:
    - dapper ci
    volumes:
    - name: docker
      path: /var/run/docker.sock
    when:
      event:
      - push
      - pull_request
      - tag

  - name: github_binary_release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      checksum:
      - sha256
      checksum_file: CHECKSUMsum-amd64.txt
      checksum_flatten: true
      files:
      - "dist/artifacts/*"
    when:
      instance:
      - drone-publish.rancher.io
      ref:
      - refs/head/master
      - refs/tags/*
      event:
      - tag

  - name: docker-publish
    image: plugins/docker
    settings:
      dockerfile: package/Dockerfile
      password:
        from_secret: docker_password
      repo: rancher/webhook-receiver
      tag: "${DRONE_TAG}"
      username:
        from_secret: docker_username
    when:
      instance:
      - drone-publish.rancher.io
      refs:
      - refs/head/master
      - refs/tags/*
      event:
      - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
